name: CI

on: [push, pull_request]

jobs:
  Test:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [22.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: ./node_modules/tree-sitter-cli/tree-sitter test

    - name: Parse LilyPond regression test files
      run: |
        git clone https://gitlab.com/lilypond/lilypond.git lilypond-source
        cd lilypond-source/input/regression
        rm bom-mark.ly other/display-lily-tests.ly
        cd ../../..
        ./node_modules/tree-sitter-cli/tree-sitter parse --quiet 'lilypond-source/**/*.ly'
      if: ${{ matrix.os != 'windows-latest' }}
